/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JComponent;
import javax.swing.border.EmptyBorder;
import main.Settings;
import main.Manager;

/**
 *
 * @author adryp
 */
public class GUIJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BufferedImage bgImage = null;
        BufferedImage voiceImage = null;
        try {
            bgImage = ImageIO.read(new File(Settings.ROOT+"src\\assets\\img\\hero_medium.jpg"));
            voiceImage = ImageIO.read(new File(Settings.ROOT+"src\\assets\\img\\wave_form_medium.png"));
        } catch (IOException e) {
            System.out.println("Image read failed!");
        }
        
        Definition = new javax.swing.JLabel("");
        BackgroundPanel1 = new ImagePanel(900, 430);
        VoicePanel1 = new ImagePanel(900, 100);
        TopBar1 = new javax.swing.JPanel();
        ResultPanel1 = new javax.swing.JPanel();
        ResultText1 = new javax.swing.JLabel();
        TitlePanel1 = new javax.swing.JPanel();
        TitleText1 = new javax.swing.JLabel();
        ContentPanel1 = new javax.swing.JPanel();
        Step1Panel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        ContinueBtn1 = new javax.swing.JButton();
        Step2Pannel1 = new javax.swing.JPanel();
        WordsPanel = new javax.swing.JPanel();
        WordBtn4 = new javax.swing.JButton();
        WordBtn5 = new javax.swing.JButton();
        WordBtn6 = new javax.swing.JButton();
        BackBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        WordBtns = new ArrayList<>();
        ContinueBtn1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        BackBtn1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        WindowSize = new javax.swing.JComboBox<>();
        
        TitleText1.setForeground(new java.awt.Color(220, 220, 220));
        TitleText1.setText("Word Sense Disambiguation");
        TitleText1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TitleText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        Definition.setForeground(Color.YELLOW);
        Definition.setFont(new java.awt.Font("Dialog", Font.ITALIC, 18)); // NOI18N
        Definition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        BackgroundPanel1.changePic(bgImage);
        VoicePanel1.setOpaque(false);
        VoicePanel1.changePic(voiceImage);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopBar1.setBackground(new java.awt.Color(0, 0, 0));
        TopBar1.setOpaque(false);

        javax.swing.GroupLayout TopBar1Layout = new javax.swing.GroupLayout(TopBar1);
        TopBar1.setLayout(TopBar1Layout);
        TopBar1Layout.setHorizontalGroup(
            TopBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TopBar1Layout.setVerticalGroup(
            TopBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        //ResultPanel1.setBackground(new java.awt.Color(255, 255, 255));
        ResultPanel1.setOpaque(false);

        ResultText1.setText("");

        javax.swing.GroupLayout ResultPanel1Layout = new javax.swing.GroupLayout(ResultPanel1);
        ResultPanel1.setLayout(ResultPanel1Layout);
        ResultPanel1Layout.setHorizontalGroup(
            ResultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultText1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        ResultPanel1Layout.setVerticalGroup(
            ResultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultText1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VoicePanel1Layout = new javax.swing.GroupLayout(VoicePanel1);
        VoicePanel1.setLayout(VoicePanel1Layout);
        VoicePanel1Layout.setHorizontalGroup(
            VoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoicePanel1Layout.createSequentialGroup()
                .addGap(900, 900, 900))
        );
        VoicePanel1Layout.setVerticalGroup(
            VoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoicePanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100))
        );

        

        javax.swing.GroupLayout TitlePanel1Layout = new javax.swing.GroupLayout(TitlePanel1);
        TitlePanel1.setLayout(TitlePanel1Layout);
        TitlePanel1Layout.setHorizontalGroup(
            TitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanel1Layout.createSequentialGroup()
                .addComponent(TitleText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );
        TitlePanel1Layout.setVerticalGroup(
            TitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanel1Layout.createSequentialGroup()
                .addComponent(TitleText1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                )
        );
        TitlePanel1.setOpaque(false);


        Step1Panel1.setBackground(new java.awt.Color(204, 204, 0));
        Step1Panel1.setOpaque(false);

        jTextField2.setText("");

        ContinueBtn1.setText("Continue");

        javax.swing.GroupLayout Step1Panel1Layout = new javax.swing.GroupLayout(Step1Panel1);
        Step1Panel1.setLayout(Step1Panel1Layout);
        Step1Panel1Layout.setHorizontalGroup(
            Step1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jTextField2)
                .addComponent(ContinueBtn1)
        );
        Step1Panel1Layout.setVerticalGroup(
            Step1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Panel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(ContinueBtn1)
                .addContainerGap())
        );

        Step2Pannel1.setBackground(new java.awt.Color(204, 204, 0));
        Step2Pannel1.setOpaque(false);
        javax.swing.GroupLayout Step2Pannel1Layout = new javax.swing.GroupLayout(Step2Pannel1);
        Step2Pannel1.setLayout(Step2Pannel1Layout);
        Step2Pannel1Layout.setHorizontalGroup(
            Step2Pannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(Step2Pannel1Layout.createSequentialGroup()
                .addGroup(Step2Pannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(Step2Pannel1Layout.createSequentialGroup()
                        .addComponent(WordsPanel)
                        )
                    .addGroup(Step2Pannel1Layout.createSequentialGroup()
                        .addComponent(BackBtn1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WindowSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                )
                .addContainerGap(125, Short.MAX_VALUE))
        );
        Step2Pannel1Layout.setVerticalGroup(
            Step2Pannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step2Pannel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(Step2Pannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WordsPanel, 30, 30, 30)
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Step2Pannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn1)
                    .addComponent(WindowSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        
        WindowSize.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 3, 5, 7, 9 }));
        WindowSize.addActionListener (new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent e) {
                Integer winSize = (Integer)WindowSize.getSelectedItem();
                performDisamb(inputTextValue, winSize);
                if (currentIndex != null)
                {
                    dis(currentIndex, winSize);
                }
            }
        });
        
        WordsPanel.setPreferredSize(new Dimension(600, 30));
        WordsPanel.setOpaque(false);
        WordsPanel.setLayout(new BoxLayout(WordsPanel, BoxLayout.LINE_AXIS));

        BackBtn1.setText("Back");

        javax.swing.GroupLayout ContentPanel1Layout = new javax.swing.GroupLayout(ContentPanel1);
        ContentPanel1.setLayout(ContentPanel1Layout);
        ContentPanel1Layout.setHorizontalGroup(
            ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanel1Layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(Step1Panel1, 300, 300, 300)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Step2Pannel1, 600, 600, 600)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        ContentPanel1Layout.setVerticalGroup(
            ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Step2Pannel1, 160, 160, 160)
                    .addComponent(Step1Panel1, 160, 160, 160))
                .addContainerGap())
        );
        ContentPanel1.setOpaque(false);

        javax.swing.GroupLayout BackgroundPanel1Layout = new javax.swing.GroupLayout(BackgroundPanel1);
        BackgroundPanel1.setLayout(BackgroundPanel1Layout);
        BackgroundPanel1Layout.setHorizontalGroup(
            BackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanel1Layout.createSequentialGroup()
                .addGroup(BackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContentPanel1, 900, 900, 900)
                    .addComponent(TitlePanel1, 900, 900, 900)
                    .addComponent(Definition, 900, 900, 900)   
                    .addComponent(VoicePanel1, 900, 900, 900))
                )
        );
        BackgroundPanel1Layout.setVerticalGroup(
            BackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, BackgroundPanel1Layout.createSequentialGroup()
                .addComponent(TitlePanel1, 60, 60, 60)
                .addGap(5, 5, 5)
                .addComponent(Definition, 40, 40, 40)
                .addGap(5, 5, 5) 
                .addComponent(ContentPanel1, 160, 160, 160)
                .addGap(5, 5, 5) 
                .addComponent(VoicePanel1, 100, 100, 100)
                .addGap(40,40,40)
                )
        );
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    ))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BackgroundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    ))
        );
        
        hideStep2();
        
        setTitle("Word Sense Disambiguation");
        setPreferredSize(new Dimension(900, 430));
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
    
    }// </editor-fold>                        

    public void dis(int index, int windowSize)
    {
        RoundButton btn_this = WordBtns.get(index);
        // reset all
        int i=0;
        for (RoundButton b:WordBtns)
        {
            b.setFocusPainted(false);
            b.setBackground(Color.WHITE);
            if (i>=index-(windowSize/2) && i<=index+(windowSize/2))
            {
                b.setBackground(Color.YELLOW);
            }
            i++;
        }
        btn_this.setBackground(Color.CYAN);
        
        String definition = manager.disambiguation(inputTextValue, index, windowSize);
        Definition.setText(definition);
        Definition.setVisible(true);
    }
    
    public void performDisamb(String inputTextValue, int windowSize)
    {
        String[] arr = inputTextValue.split(" ");    
        WordBtns.clear();
        
        Definition.setText("");
        WordsPanel.removeAll();
        int iter=0;
        int count = arr.length;
        for ( String ss : arr) {
            if (ss.isEmpty())
            {
                continue;
            }
            
            final int cindex = iter;
            RoundButton btn = new RoundButton(ss, 5);
            btn.setAlignmentX(JComponent.CENTER_ALIGNMENT);
            btn.setBackground(Color.WHITE);
            btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
            btn.addActionListener(new ActionListener()
            {
                private int index;
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    Object source = e.getSource();
                    index = cindex;
                    currentIndex = index;
                    dis(cindex, windowSize);
                }
            });
            btn.setVisible(true);
            System.out.println(ss);
            if (iter==0)
            {
                WordsPanel.add(Box.createHorizontalGlue());
            }
            else
            {
                WordsPanel.add(Box.createRigidArea(new Dimension(5,0)));
            }
            WordsPanel.add(btn);
            if (iter==count-1)
            {
                WordsPanel.add(Box.createHorizontalGlue());
            }

            WordBtns.add(btn);
            
            iter++;
        }
        WordsPanel.repaint();
        WordsPanel.revalidate();
    }

    // Variables declaration - do not modify    
    private javax.swing.JLabel Definition;
    private javax.swing.JButton BackBtn1;
    private ImagePanel BackgroundPanel1;
    private javax.swing.JPanel ContentPanel1;
    private javax.swing.JButton ContinueBtn1;
    private javax.swing.JPanel ResultPanel1;
    private javax.swing.JLabel ResultText1;
    private javax.swing.JPanel Step1Panel1;
    private javax.swing.JPanel Step2Pannel1;
    private javax.swing.JPanel TitlePanel1;
    private javax.swing.JLabel TitleText1;
    private javax.swing.JPanel TopBar1;
    private ImagePanel VoicePanel1;
    private List<RoundButton> WordBtns;
    private javax.swing.JButton WordBtn4;
    private javax.swing.JButton WordBtn5;
    private javax.swing.JButton WordBtn6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private Manager manager = null;
    private javax.swing.JPanel WordsPanel;
    private javax.swing.JComboBox<Integer> WindowSize;
    // End of variables declaration                   

    public javax.swing.JButton getContinueBtn() {
        return ContinueBtn1;
    }

    public String getInputText() {
        return jTextField2.getText();
    }

    public void showStep1() {
        Step1Panel1.setVisible(true);
    }
    
    public void showStep2() {
        Step2Pannel1.setVisible(true);
    }

    public javax.swing.JButton getBackBtn() {
        return BackBtn1;
    }
    
    public void hideStep1() {
        Step1Panel1.setVisible(false);
    }

    public void hideStep2() {
        Step2Pannel1.setVisible(false);
    }

    public void setManager(Manager man)
    {
        manager = man;
    }
    
    private String inputTextValue = "";
    private Integer currentIndex = null;

    public void setPhrase(String inputText)
    {
        final int windowSize = 3;
        inputTextValue = inputText;
        performDisamb(inputTextValue, windowSize);
    }

    public javax.swing.JLabel getDefinition() {
        return Definition;
    }
    
}
