/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import main.Manager;

/**
 *
 * @author adryp
 */
public class GUIJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BufferedImage bgImage = null;
        BufferedImage voiceImage = null;
        try {
            bgImage = ImageIO.read(new File("D:\\i am vadry\\SCARI\\WordSenseDisambiguation18\\src\\assets\\img\\hero_medium.jpg"));
            voiceImage = ImageIO.read(new File("D:\\i am vadry\\SCARI\\WordSenseDisambiguation18\\src\\assets\\img\\wave_form_medium.png"));
        } catch (IOException e) {
            System.out.println("Image read failed!");
        }
        
        
        BackgroundPanel1 = new ImagePanel(900, 400);
        VoicePanel1 = new ImagePanel(900, 100);
        TopBar1 = new javax.swing.JPanel();
        ResultPanel1 = new javax.swing.JPanel();
        ResultText1 = new javax.swing.JLabel();
        TitlePanel1 = new javax.swing.JPanel();
        TitleText1 = new javax.swing.JLabel();
        ContentPanel1 = new javax.swing.JPanel();
        Step1Panel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        ContinueBtn1 = new javax.swing.JButton();
        Step2Pannel1 = new javax.swing.JPanel();
        WordBtn4 = new javax.swing.JButton();
        WordBtn5 = new javax.swing.JButton();
        WordBtn6 = new javax.swing.JButton();
        BackBtn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        WordBtns = new ArrayList<>();

        TitleText1.setForeground(new java.awt.Color(220, 220, 220));
        TitleText1.setText("Word Sense Disambiguation");
        TitleText1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TitleText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        BackgroundPanel1.changePic(bgImage);
        VoicePanel1.setOpaque(false);
        VoicePanel1.changePic(voiceImage);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopBar1.setBackground(new java.awt.Color(0, 0, 0));
        TopBar1.setOpaque(false);

        javax.swing.GroupLayout TopBar1Layout = new javax.swing.GroupLayout(TopBar1);
        TopBar1.setLayout(TopBar1Layout);
        TopBar1Layout.setHorizontalGroup(
            TopBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TopBar1Layout.setVerticalGroup(
            TopBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        BackgroundPanel1.setBackground(new java.awt.Color(204, 0, 255));

        //ResultPanel1.setBackground(new java.awt.Color(255, 255, 255));
        ResultPanel1.setOpaque(false);

        ResultText1.setText("");

        javax.swing.GroupLayout ResultPanel1Layout = new javax.swing.GroupLayout(ResultPanel1);
        ResultPanel1.setLayout(ResultPanel1Layout);
        ResultPanel1Layout.setHorizontalGroup(
            ResultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultText1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        ResultPanel1Layout.setVerticalGroup(
            ResultPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResultText1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VoicePanel1Layout = new javax.swing.GroupLayout(VoicePanel1);
        VoicePanel1.setLayout(VoicePanel1Layout);
        VoicePanel1Layout.setHorizontalGroup(
            VoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoicePanel1Layout.createSequentialGroup()
                .addGap(900, 900, 900))
        );
        VoicePanel1Layout.setVerticalGroup(
            VoicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VoicePanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100))
        );

        

        javax.swing.GroupLayout TitlePanel1Layout = new javax.swing.GroupLayout(TitlePanel1);
        TitlePanel1.setLayout(TitlePanel1Layout);
        TitlePanel1Layout.setHorizontalGroup(
            TitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanel1Layout.createSequentialGroup()
                .addComponent(TitleText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                )
        );
        TitlePanel1Layout.setVerticalGroup(
            TitlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanel1Layout.createSequentialGroup()
                .addComponent(TitleText1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                )
        );
        TitlePanel1.setOpaque(false);


        Step1Panel1.setBackground(new java.awt.Color(204, 204, 0));
        Step1Panel1.setOpaque(false);

        jTextField2.setText("");

        ContinueBtn1.setText("Continue");

        javax.swing.GroupLayout Step1Panel1Layout = new javax.swing.GroupLayout(Step1Panel1);
        Step1Panel1.setLayout(Step1Panel1Layout);
        Step1Panel1Layout.setHorizontalGroup(
            Step1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2)
                .addContainerGap())
            .addGroup(Step1Panel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(ContinueBtn1)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        Step1Panel1Layout.setVerticalGroup(
            Step1Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Step1Panel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(ContinueBtn1)
                .addContainerGap())
        );

        Step2Pannel1.setBackground(new java.awt.Color(204, 204, 0));
        Step2Pannel1.setOpaque(false);
        Step2Pannel1.setLayout(new GridLayout(1, 0));

        WordBtn4.setText("jButton2");

        WordBtn5.setText("jButton3");

        WordBtn6.setText("jButton4");

        BackBtn1.setText("Back");
        BackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentPanel1Layout = new javax.swing.GroupLayout(ContentPanel1);
        ContentPanel1.setLayout(ContentPanel1Layout);
        ContentPanel1Layout.setHorizontalGroup(
            ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanel1Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(Step1Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Step2Pannel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        ContentPanel1Layout.setVerticalGroup(
            ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Step2Pannel1, 50, 50, 50)
                    .addComponent(Step1Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ContentPanel1.setOpaque(false);

        javax.swing.GroupLayout BackgroundPanel1Layout = new javax.swing.GroupLayout(BackgroundPanel1);
        BackgroundPanel1.setLayout(BackgroundPanel1Layout);
        BackgroundPanel1Layout.setHorizontalGroup(
            BackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanel1Layout.createSequentialGroup()
                .addGroup(BackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContentPanel1, 900, 900, 900)
                    .addComponent(TitlePanel1, 900, 900, 900)
                    .addComponent(VoicePanel1, 900, 900, 900))
                )
        );
        BackgroundPanel1Layout.setVerticalGroup(
            BackgroundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundPanel1Layout.createSequentialGroup()
                .addComponent(TitlePanel1, 100, 100, 100)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPanel1, 160, 160, 160)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoicePanel1, 100, 100, 100)
                .addGap(40,40,40)
                )
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    )
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(BackgroundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    ))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    ))
        );
        
        hideStep2();
        
        setTitle("Word Sense Disambiguation");
        setPreferredSize(new Dimension(900, 430));
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
    
    }// </editor-fold>                        

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void BackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrameLocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrameLocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrameLocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrameLocked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrameLocked().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BackBtn1;
    private ImagePanel BackgroundPanel1;
    private javax.swing.JPanel ContentPanel1;
    private javax.swing.JButton ContinueBtn1;
    private javax.swing.JPanel ResultPanel1;
    private javax.swing.JLabel ResultText1;
    private javax.swing.JPanel Step1Panel1;
    private javax.swing.JPanel Step2Pannel1;
    private javax.swing.JPanel TitlePanel1;
    private javax.swing.JLabel TitleText1;
    private javax.swing.JPanel TopBar1;
    private ImagePanel VoicePanel1;
    private List<javax.swing.JButton> WordBtns;
    private javax.swing.JButton WordBtn4;
    private javax.swing.JButton WordBtn5;
    private javax.swing.JButton WordBtn6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private Manager manager = null;
    // End of variables declaration                   

    public javax.swing.JButton getContinueBtn() {
        return ContinueBtn1;
    }

    public String getInputText() {
        return jTextField2.getText();
    }

    public void showStep1() {
        Step1Panel1.setVisible(true);
    }
    
    public void showStep2() {
        Step2Pannel1.setVisible(true);
    }

    public javax.swing.JButton getBackBtn() {
        return BackBtn1;
    }
    
    public void hideStep1() {
        Step1Panel1.setVisible(false);
    }

    public void hideStep2() {
        Step2Pannel1.setVisible(false);
    }

    public void setManager(Manager man)
    {
        manager = man;
    }
    
    private String inputTextValue = "";

    public void setPhrase(String inputText)
    {
        inputTextValue = inputText;
        String[] arr = inputText.split(" ");    
        WordBtns.clear();
        Step2Pannel1.setPreferredSize(new Dimension(400, 300));
        Step2Pannel1.removeAll();
        int count=0;
        for ( String ss : arr) {
            final int cindex = count;
            count++;
            //RoundButton btn = new RoundButton(ss, 5);
            javax.swing.JButton btn = new javax.swing.JButton(ss);
            btn.addActionListener(new ActionListener()
            {
                private int index;
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    index=cindex;
                    String butSrcTxt = e.getActionCommand();
                    String definition = manager.disambiguation(inputTextValue, index);
                    System.out.println(butSrcTxt+": def. "+definition);
                }
            });
            btn.setVisible(true);
            System.out.println(ss);
            WordBtns.add(btn);
            Step2Pannel1.add(btn);
        }
        Step2Pannel1.repaint();
        Step2Pannel1.revalidate();
    }
    
}
